title : "Statistics with Dr. Neil"

baseurl: "/statswithneil"
url: "http://statswithneil.com/"

owner:
    name:           Neil Martinsen-Burrell
    avatar:         bio-photo.jpg
    bio:            "Independent Statistics Educator"
    email:          neilmartinsenburrell@gmail.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    twitter: https://twitter.com/DrNeilMB       
    facebook:       
    github:         
    linkedin:       
    instagram:      
    lastfm:         
    tumblr:         
    # For Google Authorship https://plus.google.com/authorship
google_plus: https://google.com/+NeilMartinsenBurrell

# Analytics and webmaster tools stuff goes here
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: E6D1A4E86511139AFB44AFBE1F38C1E0       

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /about.html
  - title: Services
    url: /services.html
  - title: Contact
    url: /contact.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
